[project]
name = "big-belly-nyc"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ben Moss <ben@mossity.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
regenerate = "rm bins.db && git-history  file bins.db bins.json --id serialNumber --convert 'json.loads(content)[\"compostAssets\"]' --full-versions --namespace bin"

[dependencies]
git-history = "*"
datasette = "*"
sqlite = ">=3.47.2,<4"
